imagersite/imager_images/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.conf.urls import patterns, url
from imager_images.views import (
    LibraryView,
    PhotoView,
    AlbumView,
    FaceEditView,
    album_create,
    album_update,
    photo_create,
    photo_update
)


urlpatterns = patterns(
    '',
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^album/(?P<pk>\d+)/$', AlbumView.as_view(), name='album'),
    url(r'^photos/(?P<pk>\d+)/$', PhotoView.as_view(), name='photo'),
    url(r'^album/add/$', album_create, name='album_add'),
    url(r'^album/edit/(?P<pk>\d+)/$', album_update, name='album_edit'),
    url(r'^photos/add/$', photo_create, name='photo_add'),
    url(r'^photos/edit/(?P<pk>\d+)/$', photo_update, name='photo_edit'),
    url(r'^photos/(?P<pk>\d+)/detect/$', PhotoView.as_view(detect=True), name='detect_faces'),
    url(r'^photos/(?P<pk>\d+)/face/edit/$', FaceEditView.as_view(), name='edit_face'),
)

imagersite/imager_profile/urls.py
from django.conf.urls import patterns, url

from .views import ProfileDetailView, profile_update_view


urlpatterns = patterns(
    '',
    url(r'^$', ProfileDetailView.as_view(), name='detail'),
    url(r'^edit/$', profile_update_view, name='edit')
)

imagersite/imagersite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from .views import IndexView

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^images/', include('imager_images.urls')),
    url(r'^profile/', include('imager_profile.urls', namespace='profile'))
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

imagersite/imager_images/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


PUBLISHED_CHOICES = (
    ('private', 'private'),
    ('shared', 'shared'),
    ('public', 'public')
)


@python_2_unicode_compatible
class Photo(models.Model):
    user = models.ForeignKey(
        User,
        null=False,
        related_name='photos'
    )
    photo = models.ImageField(upload_to='photo_files/%Y-%m-%d')
    title = models.CharField(max_length=256, blank=True)
    description = models.TextField(blank=True)
    date_uploaded = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    date_published = models.DateField(null=True, blank=True)
    published = models.CharField(
        max_length=256,
        choices=PUBLISHED_CHOICES,
        default='private'
    )

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Album(models.Model):
    user = models.ForeignKey(
        User,
        null=False,
        related_name='albums'
    )
    photos = models.ManyToManyField(
        Photo,
        related_name='albums'
    )
    title = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    date_uploaded = models.DateField(auto_now_add=True)
    date_modified = models.DateField(auto_now=True)
    date_published = models.DateField(null=True, blank=True)
    published = models.CharField(
        max_length=256,
        choices=PUBLISHED_CHOICES,
        default='private'
    )
    cover = models.ForeignKey(
        Photo,
        related_name='+',
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Face(models.Model):
    photo = models.ForeignKey(
        Photo, related_name='faces', null=False
    )
    x = models.IntegerField()
    y = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    name = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return 'Face: ' + self.photo.title + ' : ' + self.name

imagersite/imager_images/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import get_object_or_404, render
from imager_images.models import Photo, Album, Face
from braces.views import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import os


def get_faces(photo):
    import Algorithmia
    import base64
    Algorithmia.apiKey = os.environ['ALGORITHMIA_KEY']
    with open(photo.photo.path, "rb") as img:
        b64 = base64.b64encode(img.read())

    result = Algorithmia.algo("/ANaimi/FaceDetection").pipe(b64)

    faces = []
    for rect in result:
        face = Face()
        face.photo = photo
        face.name = '?'
        face.x = rect['x']
        face.y = rect['y']
        face.width = rect['width']
        face.height = rect['height']
        face.save()
        faces.append(face)

    return faces


class LibraryView(LoginRequiredMixin, ListView):
    context_object_name = 'media'
    template_name = 'imager_images/library.html'

    def get_queryset(self):
        albums = self.request.user.albums.all()
        photos = self.request.user.photos.all()
        return [albums, photos]


class AlbumView(LoginRequiredMixin, ListView):
    context_object_name = 'media'
    template_name = 'imager_images/album.html'

    def get_queryset(self):
        album = get_object_or_404(Album, id=self.kwargs['pk'])
        photos = album.photos.all()
        return [album, photos]


class PhotoView(LoginRequiredMixin, DetailView):
    model = Photo
    context_object_name = 'photo'
    template_name = 'imager_images/photo.html'
    detect = False

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        if self.detect and len(self.object.faces.all()) == 0:
            get_faces(self.object)

        context['faces'] = self.object.faces.all()
        return context


@login_required
def album_create(request):
    if request.POST:
        album = Album(
            user=request.user,
            title=request.POST['title'],
            description=request.POST['description'],
            published=request.POST['published'],
            cover=Photo.objects.get(id=int(request.POST['cover']))
        )
        album.save()
        for i in request.POST.getlist('photos'):
            album.photos.add(Photo.objects.get(id=int(i)))
        album.save()

        return HttpResponseRedirect(reverse('library'))

    else:
        return render(request, 'imager_images/album_add.html')


@login_required
def album_update(request, pk):
    album = Album.objects.get(id=pk)
    if request.POST and (
        request.user == album.user or album.published == 'public'
    ):
        album.title = request.POST['title']
        album.description = request.POST['description']
        album.published = request.POST['published']
        album.cover = Photo.objects.get(id=int(request.POST['cover']))
        album.photos.clear()
        for i in request.POST.getlist('photos'):
            album.photos.add(Photo.objects.get(id=int(i)))
        album.save()

        return HttpResponseRedirect(reverse('library'))

    else:
        return render(request, 'imager_images/album_edit.html', {'album': album})


@login_required
def photo_create(request):
    if request.POST:
        photo = Photo(
            user=request.user,
            title=request.POST['title'],
            description=request.POST['description'],
            published=request.POST['published'],
            photo=request.FILES['photo']
        )
        photo.save()

        return HttpResponseRedirect(reverse('library'))

    else:
        return render(request, 'imager_images/photo_add.html')


@login_required
def photo_update(request, pk):
    photo = Photo.objects.get(id=pk)
    if request.POST and (
        request.user == photo.user or photo.published == 'public'
    ):
        photo.title = request.POST['title']
        photo.description = request.POST['description']
        photo.published = request.POST['published']
        photo.save()

        return HttpResponseRedirect(reverse('library'))

    else:
        return render(request, 'imager_images/photo_edit.html', {'photo': photo})


class FaceEditView(LoginRequiredMixin, TemplateView):
    model = Face

    def post(self, request, *args, **kwargs):
        try:
            face = Face.objects.get(id=request.POST['id'])
            face.name = request.POST['name']
            face.save()
        except (TypeError, Photo.DoesNotExist, Face.DoesNotExist):
            pass
        return HttpResponse()

imagersite/imager_images/templates/imager_images/album.html
{% extends "base.html" %}
{% load thumbnail %}
{% load images_filters %}

{% block nav_li %}
<li><a href="{% url 'profile:detail' %}">Profile</a></li>
<li><a href="{% url 'library' %}">Library</a></li>
{% endblock %}

{% block content %}
  {% if media.0|album_is_authorized:user %}
    <div class="photos">
      <div class="row">
      {% for photo in media.1|authorized_photos:user %}
        <div class="three columns">
          <a href="{% url 'photo' pk=photo.id %}">
            {% thumbnail photo.photo "200" as im %}
            <img src="{{ im.url }}">
            {% endthumbnail %}
          </a>
          <p>{{ photo.title }}</p>
        </div><!-- end column -->
      {% if forloop.counter|divisibleby:4 %}
      </div><!-- end row -->
      <div class="row">
      {% endif %}
      {% endfor %}
      </div><!-- end row -->
    </div><!-- end photos -->
  {% else %}
    <p>Not found</p>
  {% endif %}
{% endblock %}

imagersite/imager_images/templates/imager_images/album_add.html
{% extends "base.html" %}

{% block nav %}
<nav id="navbar-collapse" class="collapse u-pull-left">
  <ul class="u-cf">
    <li><a href="{% url 'profile:detail' %}">Profile</a></li>
    <li><a href="{% url 'library' %}">Library</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
    <div class="main">
        <form action="{% url 'album_add' %}" method="post">{% csrf_token %}
            <label>Title: <input type="text" name="title" id="title"></label>
            <label>Description: <input type="text" name="description" id="description"></label>
            <label>Photos: <select name="photos" size="6" multiple="multiple">
                {% for photo in user.photos.all %}
                <option value="{{ photo.id }}">{{ photo.title }}</option>
                {% endfor %}
                </select>
            </label>
            <label>Published: <select name="published">
                <option value="private">Private</option>
                <option value="shared">Shared</option>
                <option value="public">Public</option>
                </select>
            </label>
            <label>Cover: <select name="cover">
                {% for photo in user.photos.all %}
                <option value="{{ photo.id }}">{{ photo.title }}</option>
                {% endfor %}
                </select>
            </label>
            <input type="submit" name="albumadd" value="Submit" id="submit">
        </form>
    </div>
{% endblock %}

imagersite/imager_images/templates/imager_images/album_edit.html
{% extends "base.html" %}
{% load images_filters %}

{% block nav %}
<nav id="navbar-collapse" class="collapse u-pull-left">
  <ul class="u-cf">
    <li><a href="{% url 'profile:detail' %}">Profile</a></li>
    <li><a href="{% url 'library' %}">Library</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
    {% if album|album_is_editable:user %}
    <div class="main">
        <form action="{% url 'album_edit' pk=album.id %}" method="post">{% csrf_token %}
            <label>Title: <input type="text" name="title" id="title"></label>
            <label>Description: <input type="text" name="description" id="description"></label>
            <label>Photos: <select name="photos" size="6" multiple="multiple">
                {% for photo in user.photos.all %}
                <option value="{{ photo.id }}">{{ photo.title }}</option>
                {% endfor %}
                </select>
            </label>
            <label>Published: <select name="published">
                <option value="private">Private</option>
                <option value="shared">Shared</option>
                <option value="public">Public</option>
                </select>
            </label>
            <label>Cover: <select name="cover">
                {% for photo in user.photos.all %}
                <option value="{{ photo.id }}">{{ photo.title }}</option>
                {% endfor %}
                </select>
            </label>
            <input type="submit" name="albumedit" value="Submit" id="submit">
        </form>
    </div>
    {% else %}
    <p>Not found</p>
    {% endif %}
{% endblock %}

imagersite/imager_images/templates/imager_images/library.html
{% extends "base.html" %}
{% load thumbnail %}
{% load staticfiles %}

{% block nav_li %}
<li><a href="{% url 'profile:detail' %}">Profile</a></li>
{% endblock %}

{% block content %}

<section class="albums">

  <div class="row">
    <div class="two columns">
      <h3>Albums:</h3>
    </div>
    <div class="ten columns">
      <a href="{% url 'album_add' %}"><button class="button-primary u-pull-right">Add new album</button></a>
    </div>
  </div>
  
  <div class="row">
    {% for album in media.0 %}
    
    <div class="three columns">
      <a href="{% url 'album' pk=album.id %}">{{ album.title|truncatechars:26 }}</a>
      <a href="{% url 'album' pk=album.id %}">
        {% if album.cover %}
        
          {% thumbnail album.cover.photo "200x200" crop="center" as im %}
          <img src="{{ im.url }}" alt="{{ album.title }}">
          {% endthumbnail %}
        
        {% else %}
          <img src="{% static 'images/django_thumb.jpg' %}" alt="Django Unchained">
        {% endif %}
      </a>
      <a href="{% url 'album_edit' pk=album.id %}"><button>Edit</button></a>
    </div><!-- end column -->
    
  {% if forloop.counter|divisibleby:4 %}
  </div><!-- end row -->
  <div class="row">
  {% endif %}
  {% endfor %}
  </div><!-- end row -->
  <hr />
</section><!-- end albums -->

<section class="photos">

  <div class="row">
    <div class="two columns">
      <h3>Photos:</h3>
    </div>
    <div class="ten columns">
      <a href="{% url 'photo_add' %}"><button class="button-primary u-pull-right">Add new photo</button></a>
    </div>
  </div>

  <div class="row">
  {% for photo in media.1 %}
    <div class="three columns">
      <a href="{% url 'photo' pk=photo.id %}">{{ photo.title }}</a>
      <a href="{% url 'photo' pk=photo.id %}">
        {% thumbnail photo.photo "200x200" crop="center" as im %}
        <img src="{{ im.url }}" alt="{{ photo.title }}">
        {% endthumbnail %}
      </a>
      <a href="{% url 'photo_edit' pk=photo.id %}"><button>Edit</button></a>
    </div><!-- end column -->
    
  {% if forloop.counter|divisibleby:4 %}
  </div><!-- end row -->
  <div class="row">
  {% endif %}
  {% endfor %}
  </div><!-- end row -->
  <hr />
</section><!-- end photos -->
{% endblock %}

imagersite/imager_images/templates/imager_images/photo.html
{% extends "base.html" %}
{% load images_filters %}
{% load staticfiles %}

{% block css %}
  {{ block.super }}
  <link rel='stylesheet' type='text/css' href="{% static 'css/facetagger.css' %}"/>
  <link rel="stylesheet" type='text/css' href="//cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.0/sweetalert.min.css"/>
{% endblock %}

{% block nav %}
<nav id="navbar-collapse" class="collapse u-pull-left">
  <ul class="u-cf">
    <li><a href="{% url 'profile:detail' %}">Profile</a></li>
    <li><a href="{% url 'library' %}">Library</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
    {% if photo|photo_is_authorized:user %}
    <div class="main">
        <div id="photo-container">
          <img src="{{ photo.photo.url }}">
        </div>
        <h3>{{ photo.title }}</h3>
        <h4>{{ photo.user }}</h4>
        <p>{{ photo.description }}</p>
        <p>Date Uploaded: {{ photo.date_uploaded }}</p>
        <p>Date Modified: {{ photo.date_modified }}</p>
        {% if not faces %}
        <a href="{% url 'detect_faces' object.id %}"><button>Detect Faces</button></a>
        {% endif %}
    </div>
    {% else %}
    <p>Not found</p>
    {% endif %}
    
{% endblock %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
  <script type="text/javascript" src="//algorithmia.com/v1/clients/js/algorithmia-0.2.0.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/sweetalert/1.0.1/sweetalert-dev.js"></script>
  <script src="{% static 'js/facetagger.js' %}"  type="text/javascript"></script>
  <script type="text/javascript">
    FaceTagger.init({
      container: '#photo-container',
      labelUrl: '{% url "edit_face" object.id %}',
      csrf: '{{ csrf_token }}',
      originalWidth: {{ object.photo.width }},
      originalHeight: {{ object.photo.height }},
    newWidth: $("#photo-container img").width(),
    newHeight: $("#photo-container img").height()
    });
    {% for f in faces %}
      var face = {
        id: {{ f.id }},
        name: "{{ f.name }}",
        x: {{ f.x }},
        y: {{ f.y }},
        width: {{ f.width }},
        height: {{ f.height }}
      };
      FaceTagger.make(face);
    {% endfor %}
  </script>
{% endblock %}

imagersite/imager_images/templates/imager_images/photo_add.html
{% extends "base.html" %}

{% block nav %}
<nav id="navbar-collapse" class="collapse u-pull-left">
  <ul class="u-cf">
    <li><a href="{% url 'profile:detail' %}">Profile</a></li>
    <li><a href="{% url 'library' %}">Library</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
    <div class="main">
        <form action="{% url 'photo_add' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
            <label>Title: <input type="text" name="title" id="title"></label>
            <label>Description: <input type="text" name="description" id="description"></label>
            <label>Photo: <input type="file" name="photo"></label>
            <label>Published: <select name="published">
                <option value="private">Private</option>
                <option value="shared">Shared</option>
                <option value="public">Public</option>
                </select>
            </label>
            <input type="submit" name="photoadd" value="Submit" id="submit">
        </form>
    </div>
{% endblock %}

imagersite/imager_images/templates/imager_images/photo_edit.html
{% extends "base.html" %}
{% load images_filters %}

{% block nav %}
<nav id="navbar-collapse" class="collapse u-pull-left">
  <ul class="u-cf">
    <li><a href="{% url 'profile:detail' %}">Profile</a></li>
    <li><a href="{% url 'library' %}">Library</a></li>
  </ul>
</nav>
{% endblock %}

{% block content %}
    {% if photo|photo_is_editable:user %}
    <div class="main">
        <form action="{% url 'photo_edit' pk=photo.id %}" method="post">{% csrf_token %}
            <label>Title: <input type="text" name="title" id="title"></label>
            <label>Description: <input type="text" name="description" id="description"></label>
            <label>Published: <select name="published">
                <option value="private">Private</option>
                <option value="shared">Shared</option>
                <option value="public">Public</option>
                </select>
            </label>
            <input type="submit" name="photoedit" value="Submit" id="submit">
        </form>
    </div>
    {% else %}
    <p>Not found</p>
    {% endif %}
{% endblock %}