imagersite/imager_profile/urls.py
from django.conf.urls import patterns, url

from .views import ProfileDetailView, profile_update_view


urlpatterns = patterns(
    '',
    url(r'^$', ProfileDetailView.as_view(), name='detail'),
    url(r'^edit/$', profile_update_view, name='edit')
)

imagersite/imagersite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from .views import IndexView

urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^images/', include('imager_images.urls')),
    url(r'^profile/', include('imager_profile.urls', namespace='profile'))
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

imagersite/imager_profile/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class ActiveProfileManager(models.Manager):
    def get_queryset(self):
        return super(ActiveProfileManager, self).get_queryset().filter(
            user__is_active=True
        )


@python_2_unicode_compatible
class ImagerProfile(models.Model):
    user = models.OneToOneField(
        User,
        related_name="profile",
        null=False
    )
    camera = models.CharField(
        max_length=256,
        help_text="Enter your favorite camera.",
        blank=True
    )
    address = models.CharField(max_length=256, blank=True)
    web_url = models.URLField(blank=True)
    type_photography = models.CharField(
        max_length=256,
        help_text="What type of photgraphy do your prefer?",
        blank=True
    )

    objects = models.Manager()
    active = ActiveProfileManager()

    def __str__(self):
        return self.user.get_full_name() or self.user.username

    @property
    def is_active(self):
        return self.user.is_active

    def get_absolute_url(self):
        return reverse('profile:detail')

imagersite/imager_profile/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import ImagerProfile


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = ImagerProfile
        fields = ('camera', 'address', 'web_url', 'type_photography',)


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

imagersite/imager_profile/views.py
from __future__ import absolute_import

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import DetailView
from braces.views import LoginRequiredMixin

from .forms import ProfileUpdateForm, UserUpdateForm
from .models import ImagerProfile


class ProfileActionMixin(object):

    fields = ['camera', 'address', 'web_url', 'type_photography']

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        messages.info(self.request, self.success_msg)
        return super(ProfileActionMixin, self).form_valid(form)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = ImagerProfile
    template_name = "imager_profile/profile_detail.html"

    def get_object(self):
        return self.request.user


@login_required
def profile_update_view(request):
    if request.method == 'POST':
        profile_form = ProfileUpdateForm(
            request.POST, instance=request.user.profile
        )
        user_form = UserUpdateForm(
            request.POST, instance=request.user
        )
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            return HttpResponseRedirect(reverse('profile:detail'))
        else:
            context = {
                'profile_form': profile_form.as_p, 'user_form': user_form.as_p
            }
            return render(
                request, 'imager_profile/profile_edit.html', context
            )
    else:
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        user_form = UserUpdateForm(instance=request.user)
        context = {
            'profile_form': profile_form.as_p, 'user_form': user_form.as_p
        }
        return render(
            request, 'imager_profile/profile_edit.html', context
        )

imagersite/imager_profile/templates/imager_profile/profile_detail.html
{% extends "base.html" %}

{% block nav_li %}
<li><a href="{% url 'library' %}">Library</a></li>
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <div>
    <h1>Your Profile</h1>
    <ul>
      <li>Username: {{ user.username }}</li>
      <li>First name: {{ user.first_name }}</li>
      <li>Last name: {{ user.last_name }}</li>
      <li>Email: {{ user.email }}</li>
      <li>Address: {{ user.profile.address }}</li>
      <li>Website: {{ user.profile.web_url }}</li>
      <li>Camera: {{ user.profile.camera }}</li>
      <li>Type of Photography: {{ user.profile.type_photography }}</li>
      <li>Number of photos: {{ user.photos.count }}</li>
      <li>Number of albums: {{ user.albums.count }}</li>
    </ul>
  </div>
  <a href="{% url 'profile:edit' %}"><button class="button-primary">Edit Profile</button></a>
  {% endif %}
{% endblock %}

imagersite/imager_profile/templates/imager_profile/profile_edit.html
{% extends "base.html" %}

{% block nav_li %}
<li><a href="{% url 'profile:detail' %}">Profile</a></li>
<li><a href="{% url 'library' %}">Library</a></li>
{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
  {{ user_form }}
  {{ profile_form }}
  <input type="submit" value="Update Profile" class="button-primary"/>
</form>
{% endblock %}